name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and test the project inside devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make --quiet --jobs --output-sync && make --quiet check
